### ISSUE TITLE
Integration with DDL

### ISSUE THREAD

**Issue by dokshina** [tarantool/crud#27] opened 2020-09-30 08:02 UTC
Use DDL to define space schema in README in tests.

**Comment by Totktonada** [comment] 2021-06-18 23:13
I like the idea about loose coupling, proposed by @knazarov in https://github.com/tarantool/crud/issues/46#issuecomment-705634866. Not sure, whether it should use a space, but the idea in general looks nice.

**Comment by Totktonada** [comment] 2021-06-18 23:16
How #123 and #166 are related to this task (X is part of Y, Z is duplicate of A and so on)?

**Comment by Totktonada** [comment] 2021-07-23 19:16
## Proposal

I consider this issue as the task about support of an external schema provider. This proposal describes my vision of API of this external schema provider.

[tarantool/ddl](https://github.com/tarantool/ddl) is the reference schema provider and in the most cases, where I say 'schema provider', one may assume 'tarantool/ddl'.

### Schema provider API

```lua
-- Get the full space schema.
--
-- The format of the return value is described in the
-- tarantool/ddl README.
--
-- The plan is to introduce optional `sharding_func` field for a
-- space. If the field exists, the space is considered as sharded.
-- The format of the `sharding_func` field is the same as in the
-- `get_sharding_func()` function.
<schema_provider>.get_schema() -> {
    spaces = <...>
}

-- Get sharding functions for all spaces.
--
-- This information must be in-sync with one returned by
-- the `get_schema()` function.
<schema_provider>.get_sharding_func() -> {
    [space_name] = 'mpcrc32' | 'strcrc32' | 'dot.notation.func' | {body = 'function(key) return <...> end'},
    <...>
}
```

A schema provider may expose additional functions, which allow to set particular fields:

```lua
-- Set sharding function for a space.
--
-- func: 'mpcrc32' | 'strcrc32' | 'dot.notation.func' | {body = 'function(key) return <...> end'}
<schema_provider>.set_sharding_func(space_name, func)
```

However it is generally out of scope of this proposal.

### Schema consumers

A schema consumer code will look like so:

```lua
-- Use a provided schema or fail.
if rawget(_G, 'ddl') == nil or _G.ddl.get_schema == nil then
    error('No default schema provider: _G.ddl.get_schema is not available')
end
local schema = _G.ddl.get_schema()

-- If we only need information about sharding functions.
if rawget(_G, 'ddl') == nil or _G.ddl.get_sharding_func == nil then
    error('No default schema provider: _G.ddl.get_sharding_func is not available')
end
local sharding_func_map = _G.ddl.get_sharding_func()
```

### Details about tarantool/crud

In fact, tarantool/crud becomes a schema provider and a schema cunsumer at the same time.

The module provides `crud.get_schema()`, which just passes execution to `_G.ddl.get_schema()` if it exists or uses net.box information about space schema otherwise.

It saturates the net.box space schema information with data from `_G.ddl.get_sharding_func()` if it exists, otherwise say 'strcrc32' about all known spaces.

In other words:

```lua
-- Get full space schema.
--
-- The format of the return value is described in the
-- tarantool/ddl README.
--
-- This function returns the schema collected from net.box
-- connections to storages. If there is `_G.ddl.get_sharding_func()`,
-- use its information to fill `sharding_func` fields.
--
-- The function should detect recursion for the case, when
--
--  | _G.ddl = require('crud')
--
-- If the recursion is detected, fall back to the default behaviour:
-- return the net.box based space schema.
crud.get_schema() -> {
    spaces = <...>
}
```

### Follow ups

If this proposal looks good, I think we should introduce `<schema_provider>.get_sharding_key()` and `<schema_provider>.set_sharding_key(space_name, key_part_names)` similarly how it is proposed for the sharding functions and use this API in #166.

**Comment by Totktonada** [comment] 2021-07-23 19:38
Several follow ups:

- @sharonovd proposes `crud.set_schema_provider(<schema provider>)` instead of `_G.ddl = <schema provider>`. Those are not equivalent: my idea was to set a default schema provider for all who needs it (the setting to _G is weird thought, don't know an alternative). Dmitry's idea is to set a schema provider just for crud (which will cover 90% of cases anyway, I guess).
- My thought: in fact, we're not obligated to make crud a schema provider and provide `crud.get_schema()`. Let's do it only if it actually will make the code structured better. We can just make crud the user of `<schema provider>.get_schema()` and/or `<schema provider>.get_sharding_func()`.

**Comment by Totktonada** [comment] 2021-07-23 19:55
One more thought:

If we'll consider the case, when a user wants schema be collected from storages using net.box, but sharding functions from a schema provider (tarantool/ddl), as a strange wish, which should be implementable, but not necessary in a easy way, we can exclude `<schema provider>.get_sharding_func()` from the schema provider API.

So, crud will always use `<schema provider>.get_schema()` if a schema provider is set (as default / for crud). So crud without a schema provider will always use 'strcrc32' as a sharding function.

If a user want to use a custom sharding function, but keep net.box based space schema fetching, it can update its ddl schema according to what net.box reported in its own code.

And, if we'll later found that this case is actually required, we can just add `crud.set_sharding_func(space_name, key_part_names)` without any relation to the schema provider API.

**Comment by Totktonada** [comment] 2021-07-23 20:03
So now my proposal is the following:

1. Add `crud.set_schema_provider(<schema provider>)`. Calling it will replace usage of net.box's schema with usage of the schema from the schema provider (so crud will call `<schema provider>.get_schema()`).
2. Learn crud to follow `sharding_key` fields (in space definitions) from the schema provider if it is set (#166).
3. Learn tarantool/ddl to store and return `sharding_func` fields (in space definitions) from `get_schema()`.
4. Learn crud to follow `sharding_func` fields from the schema provider (if set).

**Comment by Totktonada** [comment] 2021-09-06 13:50
I changed my mind, at least in context of near tasks.

tarantool/ddl is just accessor for an instance local schema, not something like a cluster wide schema provider. So it'll collect router's local database schema when called on a router.

If we'll reconsider tarantool/ddl design together with this task, we'll pass the long way to achieve the not-to-large goal.

So I propose to stick on the simpler plan:

1. Bless `_ddl_sharding_key` space as part of the tarantool/ddl API (already done in https://github.com/tarantool/ddl/pull/65).
2. Introduce the new `_ddl_sharding_func` space as part of the API (within https://github.com/tarantool/ddl/issues/71).
3. Support collecting information from those spaces in tarantool/crud (within #166 and https://github.com/tarantool/ddl/issues/71).

And stop on it. At least, for now.

**Comment by Totktonada** [comment] 2022-05-21 19:21
All planned tasks are solved.

**Closed by Totktonada** 2022-05-21 19:21 UTC
