### ISSUE TITLE
Verify that {first = <...>} in select/pairs does not fall into full scan, when it does not

### ISSUE THREAD

**Issue by Totktonada** [tarantool/crud#238] opened 2021-11-14 19:42 UTC
See https://github.com/tarantool/crud/pull/169/files#r652086030 and https://github.com/tarantool/crud/pull/158#discussion_r653452766

**Comment by Totktonada** [comment] 2022-06-16 17:35
@oleg-jukovec Please, take a look when time will permit.

**Comment by oleg-jukovec** [comment] 2022-06-29 07:30
1. In the #158 was suggested to delete the logic of choosing bigger value from `scan value` and `after`. That would be a mistake because even in the simple example:
```
crud.select('space', {}, {after = value})
```
will be a fullscan (we will scroll from beginning of the index to `after`, otherwise we start from `after`).

We have such logic in the master:

https://github.com/tarantool/crud/blob/aea09775055ed4006efa2b480c1e97b9c7ce9691/crud/select/executor.lua#L44-L69

It works as expected.

2.  #169 adds some new tests that does not work as expected.

We have these tests (and some more tests which was broken by #177 ):

https://github.com/tarantool/crud/blob/aea09775055ed4006efa2b480c1e97b9c7ce9691/test/integration/select_test.lua#L1186-L1187

It works fine too.

I rechecked the current implementation of choosing from `scan value` and `after` + scrolling to `after`. It works as expected (at least with examples related to the issue).

It seems to me the issue is outdated. I close it.

**Closed by oleg-jukovec** 2022-06-29 07:30 UTC
Labels: teamE, code health
